feat(styles): 23 - create app_ui and make the files to manage colors and font
Flowlabsio/flutter_starter_kit pull request #1
Opened 2024-12-04 00:09 UTC by santiagoduc0s

## Description

In this PR I added the most important files of UI that usually use in the every app. Fonts, colors, and spacing. In this PR your are not finde the ```README.md``` with the guide step by step because I'm working on that (the version that was in the this repo only has the information about initialize firebase). But in general the idea is that the user create the project using vgv cli and then run a few of commands, one of them install ```app_ui``` in their project. And after that the user could start to use the package.

In this time we follow the [Material 3 standard](https://m3.material.io/) to manage the color in the app but in a simple way, nothing complicated. And we made this thinking could has an appearances dark or light.

### Light

<img width="503" alt="image" src="https://github.com/user-attachments/assets/ae873393-7fcf-4cc7-9429-15d55d317010">

### Dark

<img width="505" alt="image" src="https://github.com/user-attachments/assets/d1ee8ebb-077f-448c-a67a-2ccb8d46aee7">

Could be look difficult, but it's simple. There are 4 colors and the the different options are different tonalities those initial four colors. And of course if the designer want to add more colors, he can.

An example of this:

![Dec-03-2024 23-46-33](https://github.com/user-attachments/assets/a225aee6-c94a-4885-95e6-3fb2bbac4c1d)

That is amazing because it's invisible for the developer if he use any of the Figma templated based in Material 3, because all  fallow the same principles about colors. Of course if the user decided that they don't need to use this, the only thing that he need to do is comment this line ```darkTheme: UITheme.dark,``` in the initialization of ```MaterialApp``` and that's it.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-12-30 20:02 UTC, RafaDeMarcoo commented on kit/app_ui/lib/src/colors/ui_color_dark.dart
> +class UIColorDark extends UIColor {
Love this

2024-12-30 20:05 UTC, RafaDeMarcoo requested changes
Awesome work, I love it!!! 
I would just add the sizing constants

2024-12-30 20:05 UTC, RafaDeMarcoo commented on kit/app_ui/lib/src/ui_spacing.dart
> +}
I would like to add 
```

  // -----------------------------------------

  static const double xxxs = 0.0625 * spaceUnit;
  static const double xxs2 = 0.09375 * spaceUnit; // 1.5
  static const double xxs = 0.125 * spaceUnit;
  static const double xs = 0.25 * spaceUnit;
  static const double xs2 = 0.375 * spaceUnit;
  static const double sm = 0.5 * spaceUnit;
  static const double md = 0.75 * spaceUnit;
  static const double md2 = 0.85 * spaceUnit;
  static const double lg = spaceUnit;
  static const double lg3 = 1.125 * spaceUnit;
  static const double lg2 = 1.25 * spaceUnit;
  static const double xlg = 1.5 * spaceUnit;
  static const double lg4 = 1.625 * spaceUnit;
  static const double xlg2 = 2 * spaceUnit;
  static const double xlg3 = 2.25 * spaceUnit;
  static const double xxlg = 2.5 * spaceUnit;
  static const double xxlg2 = 3 * spaceUnit;
  static const double xxlg3 = 3.5 * spaceUnit;
  static const double xxxlg = 4 * spaceUnit;
  static const double xxxlg2 = 4.5 * spaceUnit;
  static const double xxxxlg = 5.5 * spaceUnit;
  static const double s10 = 10;

  // -----------------------------------------
```

to use in sizes, and not spacings

2025-01-02 14:24 UTC, santiagoduc0s commented on kit/app_ui/lib/src/ui_spacing.dart
> +}
I don't see in what case that could be helpful, I mean if the user want to add a custom size, he can! but in general they should use spaces, but the size of one space depend on the designer

2025-01-02 14:28 UTC, closed without merging